srcbk15mar/Adventure (copy)/BiddingBundle/Entity/BidUser.php
<?php

namespace Adventure\BiddingBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * BidUser
 */
class BidUser
{
    
    /**
     * @var integer
     */
    private $id;


    /**
     * @var integer
     */
    private $memberid;
    
    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    protected $path;
    
    public function getAbsolutePath() {
        return null === $this->path ? null : $this->getUploadRootDir() . '/' . $this->path;
    }

    public function getWebPath() {
        return null === $this->path ? null : $this->getUploadDir() . '/' . $this->path;
    }

    protected function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'image/user';
    }

    /**
     * @var string
     */
    private $phone;

    /**
     * @var string
     */
    private $address;

    /**
     * @var integer
     */
    private $zip;

    /**
     * @var string
     */
    private $country;

    /**
     * @var integer
     */
    private $memberId;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var string
     */
    private $applicantphoto;
    /**
     * 
     * @var integer
     */
    private  $status;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return BidMember
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string 
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * Set name
     *
     * @param string $name
     * @return BidUser
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return BidUser
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }
    
    /**
     * Set applicantphoto
     *
     * @param string $applicantphoto
     * @param UploadedFile $applicantphoto
     * @return BidUser 
     */
    public function setApplicantphoto(UploadedFile $applicantphoto = null)
    {
        $this->applicantphoto = $applicantphoto;

        return $this;
    }

    /**
     * Get applicantphoto
     *@return UploadedFile
     * @return string 
     */
    public function getApplicantphoto()
    {
        return $this->applicantphoto;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return BidUser
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return BidUser
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set address
     *
     * @param string $address
     * @return BidUser
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string 
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set zip
     *
     * @param integer $zip
     * @return BidUser
     */
    public function setZip($zip)
    {
        $this->zip = $zip;

        return $this;
    }

    /**
     * Get zip
     *
     * @return integer 
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * Set country
     *
     * @param string $country
     * @return BidUser
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string 
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set memberId
     *
     * @param integer $memberId
     * @return BidUser
     */
    public function setMemberId($memberId)
    {
        $this->memberId = $memberId;

        return $this;
    }

    /**
     * Get memberId
     *
     * @return integer 
     */
    public function getMemberId()
    {
        return $this->memberId;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return BidUser
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return BidUser
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreatedOnValue()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->preUpload();
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedOnValue()
    {
        $this->updatedAt = new \DateTime();
        $this->preUpload();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        // the file property can be empty if the field is not required
        if (null === $this->getApplicantphoto()) {
            return;
        }


        // use the original file name here but you should
        // sanitize it at least to avoid any security issues
        // move takes the target directory and then the
        // target filename to move to
        $this->getApplicantphoto()->move(
                $this->getUploadRootDir(), $this->path
        );

        // set the path property to the filename where you've saved the file
        // $this->path = $this->getImage()->getClientOriginalName();
        // clean up the file property as you won't need it anymore
        $this->file = null;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }

    public function preUpload() {
        if (null !== $this->getApplicantphoto()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->path = $filename . '.' . $this->getApplicantphoto()->guessExtension();
        }
    }
    
    public function __toString()
    {
        return $this->name;
    }
   
    
}

srcbk15mar/Adventure (copy)/BiddingBundle/Resources/views/User/changePassword.html.twig
{% extends "::userbase.html.twig" %}

{% block stylesheets %}
{{parent()}}
{%endblock%}

{%block title%}Welcome to Adventure Bidding System | User Profile{%endblock%} 


{% block body %}
    <!-- BEGIN BODY -->
<body class="fixed-top">

   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">

      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                  
                  <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                   <h3 class="page-title">
                     Change Password
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="index.html">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">
                           Change Password
                       </li>
                       
                   </ul>
                   <!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
           <div id="page-wraper">
                <div class="row-fluid">
                <div class="span12">
                    <!-- Acknowledgement message start -->
			{% for flashMessage in app.session.flashbag.get('notice') %} 
                            <div class="alert alert-success fade in">
                                  <button data-dismiss="alert" class="close" type="button">×</button>
                                  <h4 class="alert-heading">Success!</h4>
                                  <p>
                                      {{ flashMessage }}
                                  </p>
                              </div>
                        {% endfor %}
                        {% for flashMessage in app.session.flashbag.get('warning') %} 
                            <div class="alert alert-danger fade in">
                                  <button data-dismiss="alert" class="close" type="button">×</button>
                                  <h4 class="alert-heading">Error!</h4>
                                  <p>
                                      {{ flashMessage }}
                                  </p>
                              </div>
                        {% endfor %}
                        {% if error is not defined %}
                        {% else %}
                        {% if error %}
                            <div class="alert alert-danger fade in">
                                  <button data-dismiss="alert" class="close" type="button">×</button>
                                  <h4 class="alert-heading">Error!</h4>
                                  <p>
                                      {{ error.message }}
                                  </p>
                              </div>
                            {% endif %}
                        {% endif %}
                        <!-- Acknowledgement message end -->  
                    <!-- BEGIN ACCORDION PORTLET-->
                    <div class="widget blue">
                        <div class="widget-title">
                            <h4><i class="icon-user"></i>Change Password</h4>
						</div>
                        <div class="widget-body">
                            <div class="accordion" id="accordion1">
								<div class="accordion-group">
                                    <div id="collapse_4" class="accordion-body collapse in">
                                        <div class="accordion-inner">
                                        	<!--Submit massege-->
                                        	
                                            <form  id="change_password" method="POST" action="{{ path('adventure_update_user_password')}}" name="changepassword" enctype="multipart/form-data">      
						<label class="control-label">Current Password</label>
						<input type="password" name="currentPassword" class="m-wrap span8" required/>
						<label class="control-label">New Password</label>
						<input type="password" class="m-wrap span8" name="newPassword" required/>
						<label class="control-label">Re-type New Password</label>
						<input type="password" class="m-wrap span8" name="confirmPassword" required/>
						<div class="submit-btn">
                                                    <button class="btn btn-primary" type="submit">Save</button>
<a href="{{path('adventure_bidding_user_changepassword')}}"><button class="btn btn-default" type="button">Cancel</button></a>
                                            </div>
					</form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <!-- END ACCORDION PORTLET-->
                </div>
            </div>

            <!-- END PAGE CONTENT-->         
         </div>

            <!-- END PAGE CONTENT-->         
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->
   </div>
</body>
<!-- END BODY -->
{%endblock%}
   
{%block javascripts %}
{{parent()}}


{%endblock%}

srcbk15mar/Adventure (copy)/BiddingBundle/Resources/views/User/createRequestUser.html.twig
{% extends "::userbase.html.twig" %}

{% block stylesheets %}
{{parent()}}
{%endblock%}

{%block title%}Welcome to Adventure Bidding System | User Profile{%endblock%} 


{% block body %}
    <!-- BEGIN BODY -->
<body class="fixed-top">

<!-- BEGIN CONTAINER -->
<div id="container" class="row-fluid">
 
<!-- BEGIN PAGE -->
<div id="main-content"> 
  <!-- BEGIN PAGE CONTAINER-->
  <div class="container-fluid"> 
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
      <div class="span12"> 
        
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title"> </h3>
        <ul class="breadcrumb">
          <li> <a href="{{path('adventure_home')}}">Home</a> <span class="divider">/</span> </li>
          <li class="active"> Post Request </li>
         
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB--> 
      </div>
    </div>
    <!-- END PAGE HEADER--> 
    <!-- BEGIN PAGE CONTENT-->
    <div id="page-wraper">
      <div class="row-fluid">
        <div class="span12"> 
          <!-- BEGIN ACCORDION PORTLET-->
          <!-- Acknowledgement message start -->
			{% for flashMessage in app.session.flashbag.get('notice') %} 
                            <div class="alert alert-success fade in">
                                  <button data-dismiss="alert" class="close" type="button">×</button>
                                  <h4 class="alert-heading">Success!</h4>
                                  <p>
                                      {{ flashMessage }}
                                  </p>
                              </div>
                        {% endfor %}
                        {% for flashMessage in app.session.flashbag.get('warning') %} 
                            <div class="alert alert-danger fade in">
                                  <button data-dismiss="alert" class="close" type="button">×</button>
                                  <h4 class="alert-heading">Error!</h4>
                                  <p>
                                      {{ flashMessage }}
                                  </p>
                              </div>
                        {% endfor %}
                        {% if error is not defined %}
                        {% else %}
                        {% if error %}
                            <div class="alert alert-danger fade in">
                                  <button data-dismiss="alert" class="close" type="button">×</button>
                                  <h4 class="alert-heading">Error!</h4>
                                  <p>
                                      {{ error.message }}
                                  </p>
                              </div>
                            {% endif %}
                        {% endif %}
                        <!-- Acknowledgement message end -->  
          <div class="widget blue">
            <div class="widget-title">
              <h4><i class="icon-user"></i>Create User Request</h4>
            </div>
            <div class="widget-body">
              <div class ="row-fluid">
                <div class="span12">
                    {{form_start(Form,{'attr':{'class':'form-vertical'} })}}
                    <div class="well">
                      <h3>Trip Details </h3>
                      <hr>
                      <div class ="row-fluid">
                        <div class="span4">
                          <div class="control-group">
                            <label class="control-label" >Trip Name</label>
                            {{ form_widget(Form.name,{'attr':{'class':'input-block-level','placeholder':''} }) }} {{  form_errors(Form.name) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Duration Of Trip</label>
                            {{ form_widget(Form.day,{'attr':{'class':'span12 select2','id':'select2_sample4'} }) }} {{  form_errors(Form.day) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="form-group">
                            <label >Journey Date </label>
                            {{ form_widget(Form.dateMin,{'attr':{'class':'datepicker span5'} }) }} {{  form_errors(Form.dateMin) }}
                            To
                            {{ form_widget(Form.dateMax,{'attr':{'class':'datepicker span5'} }) }} {{  form_errors(Form.dateMax) }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="well">
                      <h3>Location Details </h3>
                      <hr>
                      <div class ="row-fluid">
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Country</label>
                            {{ form_widget(Form.country,{'attr':{'class':'span12 chzn-select','id':'select2_sample4'} }) }} {{  form_errors(Form.country) }}
                          </div>
                        </div>
                           <div class="span4">
                          <div class="form-group">
                            <label class="control-label">State</label>
                            {{ form_widget(Form.state,{'attr':{'class':'span12 chzn-select','id':'select2_sample4'} }) }} {{  form_errors(Form.country) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="control-group">
                            <label class="control-label labelmargin" >Location</label>
                            {{ form_widget(Form.location,{'attr':{'class':'input-block-level','placeholder':'Enter Location Name'} }) }} {{  form_errors(Form.location) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Zones</label>
                            <div class="controls">
                                {{ form_widget(Form.zone,{'attr':{'class':'input-block-level chzn-select'} }) }} {{  form_errors(Form.zone) }}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="well">
                      <h3> Groups Details </h3>
                      <hr>
                      <div class ="row-fluid">
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Number Of Males</label>
                            {{ form_widget(Form.male,{'attr':{'class':'span12 select2','id':'select2_sample4'} }) }} {{  form_errors(Form.male) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Number Of Females</label>
                            {{ form_widget(Form.female,{'attr':{'class':'span12 select2','id':'select2_sample4'} }) }} {{  form_errors(Form.female) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Number Of Traveller</label>
                            {{ form_widget(Form.traveler,{'attr':{'class':'span12 select2','id':'select2_sample4'} }) }} {{  form_errors(Form.traveler) }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="well">
                      <h3> Activities Details </h3>
                      <hr>
                      <div class ="row-fluid">
                        <div class="span4">
                          <div class="form-group">
                            <label class="control-label">Activities</label>
                            {{ form_widget(Form.activity,{'attr':{'class':'input-block-level chzn-select'} }) }} {{  form_errors(Form.activity) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="control-group">
                            <label class="control-label" >Pick-Up Location</label>
                            {{ form_widget(Form.pick,{'attr':{'class':'input-block-level','placeholder':'Pick-Up Location'} }) }} {{  form_errors(Form.pick) }}
                          </div>
                        </div>
                        <div class="span4">
                          <div class="control-group">
                            <label class="control-label" >Drop-Off Location</label>
                            {{ form_widget(Form.down,{'attr':{'class':'input-block-level','placeholder':'Drop Location'} }) }} {{  form_errors(Form.down) }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="well">
                      <h3> Other Details </h3>
                      <hr>
                    <div class ="row-fluid">
                      
                      <div class="span12">
                        <div class="control-group">
                          <label class="control-label">If your group size is too small for an organizer to respond, are you open for us to combine your group with others who are looking for the exact or similar trips?  </label>
                          <div class="controls">
                              {{ form_widget(Form.team) }} {{  form_errors(Form.team) }}
                          </div>
                        </div>
                        
                      </div>
                       </div>
                       <hr>
                       <div class ="row-fluid">
                      <div class="span12">
                        <div class="control-group">
                          <label class="input-block-level"> Special Requirement: </label>
                          <div class="controls">
                              {{ form_widget(Form.description,{'attr':{'class':'span12'} }) }} {{  form_errors(Form.description) }}
                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
                    {{ form_rest(Form) }}
                    <div class="form-actions">
                      <button class="btn btn-primary" id="save" type="submit"> Submit</button>
                      <button type="button" class="btn btn-default">Cancel</button>
                    </div>
                  {{form_end(Form)}}
                </div>
              </div>
            </div>
            <!-- END ACCORDION PORTLET--> 
          </div>
        </div>
        
        <!-- END PAGE CONTENT--> 
      </div>
      
      <!-- END PAGE CONTENT--> 
      
    </div>
    
    <!-- END PAGE CONTAINER--> 
  </div>
  <!-- END PAGE --> 
</div>
<!-- END CONTAINER --> 
</div>
</body>
<!-- END BODY -->
{%endblock%}
   
{%block javascripts %}
{{parent()}}
    <script type="text/javascript">
		$(document).ready(function() {
		$('.multipl').multiselect();
		});
	</script> 
    <script type="text/javascript">
    $('#example-single-selected').multiselect();
    </script> 
    <script>
    $('.datepicker').datepicker({
        format: 'mm/dd/yyyy',
        startDate: '-3d'
    })
    
    
    function getValue(){
        var a = document.getElementById('userRequest_male').value;
        var b = document.getElementById('userRequest_female').value;
          
        var c = parseInt(a) + parseInt(b) ;
        document.getElementById('userRequest_traveler').value = c ; `
    }
    </script> 

{%endblock%}

srcbk15mar/Adventure (copy)/BiddingBundle/Resources/views/User/registerUser.html.twig
Complete USER Registeration: 

{% if message is defined %}
      {{message}}
{% endif %}


{{form_start(Form)}}
    <br>
    Name : {{ form_widget(Form.name) }} {{  form_errors(Form.name) }}<br>
    Email : {{ form_widget(Form.email) }} {{  form_errors(Form.email) }}<br>
    Phone : {{ form_widget(Form.phone) }} {{  form_errors(Form.phone) }}<br>
    Address : {{ form_widget(Form.address) }} {{  form_errors(Form.address) }}<br>
    Zip : {{ form_widget(Form.zip) }} {{  form_errors(Form.zip) }}<br>
    Country : {{ form_widget(Form.country) }} {{  form_errors(Form.country) }}<br>
    Image : {{ form_widget(Form.applicantphoto) }} {{  form_errors(Form.applicantphoto) }}
    {{ form_rest(Form) }}
    <button class="btn btn-success" id="save" type="submit"> <i class="icon-ok"></i>Submit</button>
{{form_end(Form)}}
    

srcbk15mar/Adventure (copy)/BiddingBundle/Resources/views/User/viewCloseRequest.html1.twig
{% if message is defined %}
      {{message}}
{% endif %}<br><br>

View Close Request-Response<br><br><br>

User Request Details :<br><br><br> 

    
    Trip Name : {{request.name}}<br>
    No of Males: {{request.male}}<br>
    No Of Females : {{request.female}}<br>
    No Of Travellers : {{request.traveler}}<br>
    Pick-Up Location : {{request.pick}}<br>
    Drop Location : {{request.down}}<br>
    Trip Tentative (in days) : {{request.day}}<br>
    
    Combine Group : {% if(request.team=='1')%}Yes{% else %}No{% endif %}<br>

{#Activities : {{request.activity}}<br>#}

    

Location : {{request.location}}<br><br><br><br> 

    
Organiser Response Details :<br><br><br> 


    AnyParticular Months : <br>
    Cost Include: <br>
    Cost Exclude : <br>
    Quotations : <br>
    Pick-Up Location : <br>
    Drop Location : <br><br>
    Short Details :<br>

srcbk15mar/Adventure (copy)/BiddingBundle/Resources/views/User/viewProfileUser.html.twig
{% extends "::userbase.html.twig" %}

{% block stylesheets %}
{{parent()}}
{%endblock%}

{%block title%}Welcome to Adventure Bidding System | User Profile{%endblock%} 


{% block body %}
<body class="fixed-top">
  
   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                  <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                   <h3 class="page-title">
                     
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="index.html">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">
                           My Profile <span class="divider">/</span>
                       </li>
                       <li class="active">
                           View Profile
                       </li>
                   </ul>
                   <!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
           <div id="page-wraper">
                <div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN ACCORDION PORTLET-->
                    <div class="widget blue">
                        <div class="widget-title">
                            <h4><i class="icon-user"></i>View User Inforation</h4>
						</div>
                        <div class="widget-body">
                            <div class="accordion" id="accordion1">
                                <div class="accordion-group">
                                   
                                    <div id="tab1" class="accordion-body collapse in">
                                        <div class="accordion-inner">
                                           <div class="span3">
                                                 <img src="{{asset(member.webPath)}}" alt="">
                                             </div>
                                             <div class="span9">
                                                <h4><b>Full Name : Aeon Logiciel</b></h4>
                                                 <ul class=" unstyled amounts">
                                                     <li>User Name	: {{member.name}}</li>
                                                     <li>Email		: {{member.email}}</li>
                                                     <li>Phone No.	: {{member.phone}}</li>
                                                     <li>Address	: {{member.address}}</li>
                                                     <li>Area Code	: {{member.zip}}</li>
                                                     <li>Country	: {{member.country}}</li>
                                                    
                                                 </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                
                                
                            </div>
                        </div>
                    <!-- END ACCORDION PORTLET-->
                </div>
            </div>

            <!-- END PAGE CONTENT-->         
         </div>

            <!-- END PAGE CONTENT-->         
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->
   </div>
</body>
{%endblock%}
   
{%block javascripts %}
{{parent()}}


{%endblock%}